version: '3.8'

services:
  nginx:
    container_name: postagram_web
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads_volume:/app/uploads
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    container_name: postagram_api
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn CoreRoot.wsgi:application --bind 0.0.0.0:8000"
    volumes:
     - .:/app
     - uploads_volume:/app/uploads
    depends_on:
     - db
  db:
    container_name: postagram_db
    image: postgres:14.3-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  uploads_volume:
  postgres_data:
